---
version: '3.5'
services:

  nginx-proxy:
    image: reiz/nginx_proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-aws-sqs-source/nginx-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-sqs
    #dns: 0.0.0.0