---
services:
  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-sqs
      AWS_REGION: $AWS_REGION
      # with v2 connector config is not working, need to use env variables
      AWS_STS_ROLE_ARN: $AWS_STS_ROLE_ARN
      AWS_STS_SESSION_NAME: "session-name"
      AWS_STS_EXTERNAL_ID: "123"
      AWS_ACCOUNT_WITH_ASSUME_ROLE_AWS_ACCESS_KEY_ID: $AWS_ACCOUNT_WITH_ASSUME_ROLE_AWS_ACCESS_KEY_ID
      AWS_ACCOUNT_WITH_ASSUME_ROLE_AWS_SECRET_ACCESS_KEY: $AWS_ACCOUNT_WITH_ASSUME_ROLE_AWS_SECRET_ACCESS_KEY