---
version: '3.5'
services:
  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-cdc-oracle19-source/ora-setup-scripts-cdb-table:/opt/oracle/scripts/setup
      - ../../connect/connect-cdc-oracle19-source/ora-startup-scripts-cdb-table:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: Admin123

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - oracle
    volumes:
        - ../../reproduction-models/connect-connect-jms-oracle19-sink/ojdbc8.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/ojdbc8.jar
        - ../../reproduction-models/connect-connect-jms-oracle19-sink/aqapi.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/aqapi.jar
        - ../../reproduction-models/connect-connect-jms-oracle19-sink/jta-1.1.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/jta-1.1.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink
