language: java
jdk: openjdk8
os: linux
services: docker
cache:
  directories:
  - "$HOME/.m2"
before_install:
- sudo apt-get -y install expect awscli
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p $HOME/.aws
- cp aws_config $HOME/.aws/config
- cp aws_credentials $HOME/.aws/credentials
- mkdir -p $HOME/.ccloud
- cp config.cc.vsaboulin.travis $HOME/.ccloud/config
- aws s3 cp s3://kafka-docker-playground/3rdparty/3rdparty.tgz .
- tar xvfz 3rdparty.tgz
- cp ./3rdparty/TIB_ems-ce_8.5.1_linux_x86_64.zip ./connect/connect-tibco-source/docker-tibco/TIB_ems-ce_8.5.1_linux_x86_64.zip
- cp ./3rdparty/TIB_ems-ce_8.5.1_linux_x86_64.zip ./connect/connect-jms-tibco-sink/docker-tibco/TIB_ems-ce_8.5.1_linux_x86_64.zip
- cp ./3rdparty/TIB_ems-ce_8.5.1_linux_x86_64.zip ./connect/connect-tibco-sink/docker-tibco/TIB_ems-ce_8.5.1_linux_x86_64.zip
- cp ./3rdparty/TIB_ems-ce_8.5.1_linux_x86_64.zip ./connect/connect-jms-tibco-source/docker-tibco/TIB_ems-ce_8.5.1_linux_x86_64.zip
- cp ./3rdparty/ojdbc6.jar ./connect/connect-jdbc-oracle11-sink/ojdbc6.jar
- cp ./3rdparty/ojdbc6.jar ./connect/connect-jdbc-oracle11-source/ojdbc6.jar
- cp ./3rdparty/ojdbc8.jar ./connect/connect-jdbc-oracle12-sink/ojdbc8.jar
- cp ./3rdparty/ojdbc8.jar ./connect/connect-jdbc-oracle12-source/ojdbc8.jar
- cp ./3rdparty/ImpalaJDBC42.jar ./connect/connect-kudu-source/ImpalaJDBC42.jar
- cp ./3rdparty/ImpalaJDBC42.jar ./connect/connect-kudu-sink/ImpalaJDBC42.jar
- cp ./3rdparty/jms.jar ./connect/connect-ibm-mq-sink/jms.jar
- cp ./3rdparty/jms.jar ./connect/connect-ibm-mq-source/jms.jar
- cp ./3rdparty/com.ibm.mq.allclient.jar ./connect/connect-ibm-mq-sink/com.ibm.mq.allclient.jar
- cp ./3rdparty/com.ibm.mq.allclient.jar ./connect/connect-ibm-mq-source/com.ibm.mq.allclient.jar
- cp ./3rdparty/mysql-connector-java-5.1.45.jar ./ccloud/ccloud-demo/mysql-connector-java-5.1.45.jar
- cp ./3rdparty/mysql-connector-java-5.1.45.jar ./connect/connect-debezium-mysql-source/mysql-connector-java-5.1.45.jar
- cp ./3rdparty/mysql-connector-java-5.1.45.jar ./connect/connect-jdbc-mysql-sink/mysql-connector-java-5.1.45.jar
- cp ./3rdparty/mysql-connector-java-5.1.45.jar ./connect/connect-jdbc-mysql-source/mysql-connector-java-5.1.45.jar
- cp ./3rdparty/RedshiftJDBC4-1.2.20.1043.jar ./connect/connect-aws-redshift-sink/RedshiftJDBC4-1.2.20.1043.jar
- cp ./3rdparty/activemq-all-5.15.4.jar ./connect/connect-jms-active-mq-sink/activemq-all-5.15.4.jar
- cp ./3rdparty/commons-lang-2.6.jar ./connect/connect-jms-solace-sink/commons-lang-2.6.jar
- cp ./3rdparty/sol-jms-10.6.4.jar ./connect/connect-jms-solace-sink/sol-jms-10.6.4.jar
- cp ./3rdparty/sol-jms-10.6.4.jar ./connect/connect-solace-sink/sol-jms-10.6.4.jar
- cp ./3rdparty/sol-jms-10.6.4.jar ./connect/connect-solace-source/sol-jms-10.6.4.jar
- cp ./3rdparty/AMPS.tar.gz ./connect/connect-amps-source/docker-amps/AMPS.tar.gz
- cp ./3rdparty/pivotal-gemfire.tgz ./connect/connect-pivotal-gemfire-sink/docker-pivotal-gemfire/pivotal-gemfire.tgz
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jobs:
  include:
  - name: Update README
    script: bash scripts/launch-github-action.sh
  - name: '6.0.0: CONNECT: salesforce-bulkapi-sink salesforce-bulkapi-sink salesforce-cdc-source
      salesforce-platform-events-sink salesforce-platform-events-source salesforce-pushtopics-source salesforce-sobject-sink salesforce-cdc-source salesforce-platform-events-sink salesforce-platform-events-source'
    env: TEST_LIST="connect/connect-salesforce-bulkapi-sink connect/connect-salesforce-bulkapi-source connect/connect-salesforce-pushtopics-source connect/connect-salesforce-sobject-sink connect/connect-salesforce-cdc-source connect/connect-salesforce-platform-events-sink connect/connect-salesforce-platform-events-source" TAG="6.0.0"
  - name: '6.0.0: CONNECT: azure-data-lake-storage-gen1-sink azure-data-lake-storage-gen2-sink
      azure-event-hubs-source'
    env: TEST_LIST="connect/connect-azure-data-lake-storage-gen1-sink connect/connect-azure-data-lake-storage-gen2-sink
      connect/connect-azure-event-hubs-source" TAG="6.0.0"
  - name: '6.0.0: CONNECT: azure-sql-data-warehouse-sink azure-search-sink ftps-source ftps-sink rabbitmq-sink amps-source jira-source github-source pivotal-gemfire-sink'
    env: TEST_LIST="connect/connect-azure-sql-data-warehouse-sink connect/connect-azure-search-sink connect/connect-ftps-source connect/connect-ftps-sink connect/connect-rabbitmq-sink connect/connect-amps-source connect/connect-jira-source connect/connect-github-source connect/connect-pivotal-gemfire-sink"
      TAG="6.0.0"
  - name: '6.0.0: CONNECT: azure-service-bus-source azure-blob-storage-sink
      azure-blob-storage-source mapr-sink'
    env: TEST_LIST="connect/connect-azure-service-bus-source connect/connect-azure-blob-storage-sink
      connect/connect-azure-blob-storage-source connect/connect-mapr-sink" TAG="6.0.0"
  - name: '6.0.0: CONNECT: splunk-sink splunk-source spool-dir-source syslog-source
      OTHER: override-policy-sftp-sink override-policy-sftp-source'
    env: TEST_LIST="connect/connect-splunk-sink connect/connect-splunk-source connect/connect-spool-dir-source
      connect/connect-syslog-source other/connect-override-policy-sftp-sink other/connect-override-policy-sftp-source"
      TAG="6.0.0"
  - name: '6.0.0: CONNECT: active-mq-sink active-mq-source cassandra-sink couchbase-sink
      couchbase-source'
    env:
    - TEST_LIST="connect/connect-active-mq-sink connect/connect-active-mq-source connect/connect-cassandra-sink
      connect/connect-couchbase-sink connect/connect-couchbase-source connect/connect-hbase-sink"
      TAG="6.0.0"
  - name: '6.0.0: CONNECT: jms-tibco-sink jms-tibco-source debezium-mongodb-source
      debezium-mysql-source debezium-postgresql-source debezium-sqlserver-source elasticsearch-sink datadiode'
    env: TEST_LIST="connect/connect-jms-tibco-sink connect/connect-jms-tibco-source
      connect/connect-debezium-mongodb-source connect/connect-debezium-mysql-source
      connect/connect-debezium-postgresql-source connect/connect-debezium-sqlserver-source
      connect/connect-elasticsearch-sink connect/connect-datadiode-source-sink" TAG="6.0.0"
  - name: '6.0.0: CONNECT: hbase-sink hdfs2-sink hdfs3-sink hdfs3-source hdfs2-source
      ibm-mq-sink ibm-mq-source snmp-source'
    env: TEST_LIST="connect/connect-hdfs2-sink connect/connect-hdfs2-source connect/connect-hdfs3-sink
      connect/connect-hdfs3-source connect/connect-ibm-mq-sink connect/connect-ibm-mq-source connect/connect-snmp-source"
      TAG="6.0.0"
  - name: '6.0.0: CONNECT: jdbc-oracle11-sink jdbc-oracle11-source influxdb-sink
      influxdb-source jdbc-mysql-sink jdbc-mysql-source jdbc-postgresql-sink jdbc-postgresql-source
      jdbc-sqlserver-sink'
    env: TEST_LIST="connect/connect-jdbc-oracle11-sink connect/connect-jdbc-oracle11-source
      connect/connect-influxdb-sink connect/connect-influxdb-source connect/connect-jdbc-mysql-sink
      connect/connect-jdbc-mysql-source connect/connect-jdbc-postgresql-sink connect/connect-jdbc-postgresql-source
      connect/connect-jdbc-sqlserver-sink" TAG="6.0.0"
  - name: '6.0.0: CCLOUD ccloud-demo CONNECT: jdbc-sqlserver-source jdbc-vertica-sink
      jms-active-mq-sink jms-solace-sink'
    env: TEST_LIST="ccloud/ccloud-demo connect/connect-jdbc-sqlserver-source connect/connect-jdbc-vertica-sink
      connect/connect-jms-active-mq-sink connect/connect-jms-solace-sink" TAG="6.0.0"
  - name: '6.0.0: CONNECT: mongodb-sink mongodb-source mqtt-sink mqtt-source
      neo4j-sink omnisci-sink tibco-sink tibco-source jdbc-oracle12-sink jdbc-oracle12-source'
    env: TEST_LIST="connect/connect-mongodb-sink connect/connect-mongodb-source connect/connect-mqtt-sink
      connect/connect-mqtt-source connect/connect-neo4j-sink connect/connect-omnisci-sink
      connect/connect-tibco-sink connect/connect-tibco-source connect/connect-jdbc-oracle12-sink
      connect/connect-jdbc-oracle12-source" TAG="6.0.0"
  - name: '6.0.0: CONNECT: rabbitmq-source redis-sink replicator sftp-sink
      sftp-source solace-sink solace-source'
    env: TEST_LIST="connect/connect-rabbitmq-source connect/connect-redis-sink connect/connect-replicator
      connect/connect-sftp-sink connect/connect-sftp-source connect/connect-solace-sink
      connect/connect-solace-source" TAG="6.0.0"
  - name: '6.0.0: CONNECT: aws-cloudwatch-logs-source aws-cloudwatch-metrics-sink
      aws-dynamodb-sink aws-kinesis-source aws-lambda-sink'
    env: TEST_LIST="connect/connect-aws-cloudwatch-logs-source connect/connect-aws-cloudwatch-metrics-sink
      connect/connect-aws-dynamodb-sink connect/connect-aws-kinesis-source connect/connect-aws-lambda-sink"
      TAG="6.0.0"
  - name: '6.0.0: CONNECT: gcp-bigquery-sink google-cloud-functions-sink vertica-sink
      prometheus-sink aws-sqs-source aws-s3-sink aws-s3-source'
    env: TEST_LIST="connect/connect-gcp-bigquery-sink connect/connect-gcp-cloud-functions-sink
      connect/connect-vertica-sink connect/connect-prometheus-sink connect/connect-aws-sqs-source
      connect/connect-aws-s3-sink connect/connect-aws-s3-source" TAG="6.0.0"
  - name: '6.0.0: CONNECT: gcp-pubsub-source gcs-sink gcs-source'
    env: TEST_LIST="connect/connect-gcp-pubsub-source connect/connect-gcp-gcs-sink
      connect/connect-gcp-gcs-source" TAG="6.0.0"
  - name: '6.0.0: CONNECT: http-sink'
    env: TEST_LIST="connect/connect-http-sink" TAG="6.0.0"
  - name: '6.0.0: REPLICATOR: connect'
    env: TEST_LIST="replicator/connect" TAG="6.0.0"
  - name: '6.0.0: mirrormaker2 ksqldb/materialized-view'
    env: TEST_LIST="replicator/mirrormaker2 ksqldb/materialized-view" TAG="6.0.0"
script:
- bash scripts/run-tests.sh "$TEST_LIST" "$TAG"
env:
  global:
  - secure: MxiEqV65Nfky5XzyOyElr7hTo7IaAiXTjyRkFg+h+EdaaVRpu+WrGy4dLtxKcbjJJKXB2hIVoLPbnm/RLyFIJKc06zV+EMfbXqGJ9kw5qtKnCO1xf9uqw8RsY54Szyz4JgV3Q8AvgM9wN2k/53SOQCEqMV3o5jQMLzyU6AxosR/H28Zu9359mCxjzq8S2w3Gt7PXeNCInc8HS7UeWWftLvq/SJWWb6v8WFYWSYzUmb5kAnz/JwSvW4hUv7ubSE27GbFO4KA/7nNkHsCI3zEnSMI2g0rDmbvoknD0BF/g6gChFnc8hmIp0KGkguAFog0YhLOZbXtMllbhjDpeKMHDKwd0cd0laQjsesMIq4TcSAcQlid4lmBpJA5FibNWB6gMUKjVfjlcfRpT8aMmAYXfzHGgMTpWLUQgs6FXiCFx+L8SK3cxyFHHjkvaBlkdDfVjkSSoKmBP3pcZR4c4pm4k8EKKJulsEghYh3Gjd+117SkJJeW0CtuzxBXaUOyE6yIElLWKNZdYYI52EFaFJwWBsuhKwkqJ4bT0lb9LdMofgSMvz/KVGaXua5/bdAQo3RZyDJsyf5sZC6aMroX/B09erW5Y8gt96Iptn6VSqF1mGt6KDCG7Vto2yeUflSxx/1UC/VPfG7BP0Sz00tVnoDKmHZESTi0slMR1TtKhr5EC2kU=
  - secure: K48g2ABWlEpkd8y37BT/8E6S2f2qbiwuYYKdm7v9RL7Uo0Lcp9cxXISBP7J8pWfWx626iYF2wqQ5n0Dpjd/eHjbxv4Zmfg2fX7m8nVGhezfZg3KwEyGYv2KxPbhCneoX7FxpYAMljJk+BpZxIJ+MF8uh5A9gMlglM4O1tk7b0I+hypOmScu0EOV1tAklWlgZr/D8hVxyrOLEeZ9MIwpTsw8sHImt4JX5iTP95aCkEzzPODkkgKCWgG6Gt8tQHlOMyy/VgaijxSx0X8s9vy9SWTvlOGnnWekaRE4bP8mP45pWBeSRhP1n3InFUMJVD3aC6V7Ftdcl9f/L10/D9ld7rM7sxnJCF0RKcxK7L02J6puEI+PEhDjNYXrwDBLIO3rZqhfG7v7h2RYvHCh4zbizcex10dc9qYw3RzjmZBIsvxcu2LpYFaYHIq4vqD0+a6V0DjGIUnaQYgbIAFV/YtZGZnkvBbF11hzLtUg51Ud0QzY5nyAj9lCv5W01BXbdU8/bydJKm8vvnUeGz3qIg3xdsQG4OkZTBPqt7v14PXYPwqgkUwgxyh0ihwUVD8HAHjDrEu3pfgYAcEB7IEwdYu3aWvpEqSkCESvPS9NgJYV4mr+gR4saDH3f2Ev3hb0jpYTmN8yJ6I/1grRXR4+x+0mfjXv7UP5SxAP6LcDL6mvDQBo=
  - secure: hPgFrNsSUvAZ59bMPtgLt0nsHkDhVh2MDHDdw15/C5UqCDF6t+CczVqWaG9NLnVdtpfE6lvSnwr+vmY3uHoEos6N6BrRN2G8WcGRc47b5XXV4H42lYh29M2Jsm9RW6cByupbiXFYS41DErPGFTk+/A5nPX8UvsWlq+I1rh5t2OGFHupvr3sra6jqiS5G9Fz/ecYqFSo8RfhGd71gG49EbAEu37/7Fx/npB8OfYw7V2SSa4yz8k1uynsQu2DfiOlpD1KDZX05LBHCUlz9OsPL3SYsprC/+3Un9IHQAWdXq5B9HJkMVYzwg5kD7xpEG5FtRvRUgx2YpWEGxJbCK8QhrwufGSbNsdmFrlpHp3MOrRlW7FUlnKetLzvEhmN/HzjCG4rs9aY4t9qy+zSZqfejl18gFdIwGnXDKVv7gX/2Yp6jm/K+jxaPnMsRBo64pRbXDnhsw7MMZgxtbVlL7kgMqbExpug5ItNub4nbBeoTktXXIxTqb8TkON1RM99cJNGZlo6x7Nku6HJgWn5ZdQHbhNELGEl9ah9bK8tqhm5GLHXXtv2EE4QHXpJRum11QYh0XWp9YE6Q82jLFST3MxNGEMPfj4ht3qAMLx943EUEv6bdR2f37YSu/4fOp6vh2f4LBUDik8TEF8RY/n1w9Myz7ksjyTSDCGgs5cEM424ce9w=
  - secure: v8GlSk/ibIDCgUJIHmhx8PtmvW9PCsPe8zShgS8Fj8Cd4Sc4OsxAkm45L/PXg7fKyNgo+MdCAo4foTdcvuDMychEAqCRDurcvRJ/aBKH65goS1tD8I/FpprJmSOpCirIMSz8NV4dKPyIXj8L/xpkALpavLBj252lIrCC9xWRttetuNuNxZcU8G9m5ww8jjwjMGRWYOSq9lOMn/d5txxafsxLFGvCrmrrAVfjCHrjuJbI9AfydfOhKsvd58UByESSvEPzoxNxntZE600Gr9g9RFSIDIJ4aRvybIKTI/eOZzQBxVwrAXpNAMCRwioAzMLk0ZCtmmu7tmBofthx2FEvCF0VNEvmfAdM6treazXsUjXBMc1DWeZATuEtcTcVvKgsiTZxW5VbMGiRL2pWDRmkhS26vGm8jxB+D751q+AiMFWhLX1zbmcnkBCAD8p5rNlc2t9++8euwh7EarJIZjt8N3R0mkjqWzYrCcS6DxoAdg7Y7cydvXKkY7IIqfHs28bvZqp0ARLcSMuqCvQEFfjETBQoipeadPfby/57K42lAymyqK4hDBxJWPcv7cuFUgTgiwT3rmy32mteZxuH7wl7T00YietsVgaxeKgjuKTNhQTytUJILwBBEIKOr08/i8Y9wtnJxwniLLCnbpRdW6Gj74J3BzgoaWtj6seG/NyCWXw=
  - secure: V1+uY5YZ0NQXKtHweTnYwkl9FrMFWjsr148Eno2Bjddx6nxLE33/2b2Z6iqGcv+QiphC/J+zgEAJsxk9KU25vTSurPh2w5BDDeJiGPOusrnZGqJHclhMocVGXCQ0ePWNTBHNN5xjX8PsWcGq64AEO4h4fFuhJprlFk2ZCc4gmUBX8jVNFh/hNbgFrPFSiITY+6tCe/+7bdJELuW4a5a+hw3TaDzWKodS6kXDZbn9fk1+hlRTDFQUCpLKEakAuNmEb9go3fKfxUZFlZZ9qeHP1l712IW9t58nijZidCdMMPtXRNY2Ew7pjT7gmImStEfwQIw5AdPK9WeBsXWuMBfyQOZQ4ocdIwCv4dQcROpqsJ/TkKhBF6ZJHD1Hx0534xmbrZDZMvoRZJ+7HySblF1yb6z5r94/9SV5MchjAmHbtlpSzSrK5XwyImPm1NdslgoaQPb/IeVieAtls98PSuYJ9nKMcrqQ8hDDhbEW1DWBafS+5sFpSx2GaBImNizN7nvGtUXTICom1sPukaXgf3UEt2HAl7hk6SaCH+S3sp4xWXGBe7uuIP8WLLh/cWRNjpQFWR4/wE8LCIsPLB2mrPknLBZgUMmPJfsPzRPN1FX2chp4ZwFi3eUzZwk3txzQCTyBlhcEDKYIcQ8ozNmj1CP0wwjAKC9B0B6M6/kKEqAh7cw=
  - secure: KGbBN4yz7yDdmiQ0RhohyCj1DxJL9E8Zmzj2+9cjxQOpbmKY5cwr0UiCIr6ZiYEfitPzGgrH7Z3+1K1dfFbsQ4PDsha0bW8qb0Hvgvx+DXS/Kg8ywCXaZiuNMO0Ye1RwvpVsK0U3qRRpuoyy/uLndOLzwUi8Q1jU9D4HaKkicXv/BrRlKrhmPhtF0dRopQ8qIQLNSVOVHfuR2/WIB1Dh9EIo1mK+8Y6q2IVznIbh+BlycMGpNsh++ZBhHvcr03CcrIiQvz2M8VjtZoChe0HwWlAZ+YwfCWifwwu0mK7TQ6vU8SXpXQLmK2IYrtSwknRbEiEGCVYS4+ggTG8DGzygf2b2hSYU0ZyXxAqbgPj0iZ92+di5Sw3+v7MiQYLKjWwv+lqHsxMV3229dw9cs6p/t6kG7GqM8Qzx2ggLpa6d4QdvwLYXQaWtx1+IDYqmkU2fQAcqL0aR8YvWWZ29kgY3sbFlMWggZTEOVYkCpaSkOoZEk+nBQ2COHRJQnvQn5LM9jjtEw8iahJ5SARLc4PpBIhh+ta/O/ij8nerWJqgXbTwjYKhaHvySKcWHPX5aKsqKkflQfDePtcXxg3BABO0psd2FInP7iZTtpqYwxZe+VJz+vvzBD/CKXJhWP8nFPkwdEZMn0JAX2hFyJCU4xtEXUdr//Ya6pekorIrESKGK7B0=
