---
services:
  connect:
    volumes:
        - ../../connect/connect-gcp-dataproc-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-gcp-dataproc-sink