---
services:
  connect:
    volumes:
        - ../../connect/connect-gcp-google-pubsub-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/java/,/usr/share/confluent-hub-components/