---
services:
  connect:
    volumes:
      - ../../connect/connect-jdbc-azure-synapse-analytics-source/data:/data
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
