---
services:

  mosquitto:
    image: eclipse-mosquitto:1.6.13
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - ../../connect/connect-mqtt-sink/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../../connect/connect-mqtt-sink/password:/etc/mosquitto/passwd

  connect:
    depends_on:
      - mosquitto
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-mqtt