---
services:
  solace:
    image: solace/solace-pubsub-standard:10.2
    hostname: solace
    container_name: solace
    user: root
    volumes:
      - ../../connect/connect-jms-solace-source/create_queue_cmd:/usr/sw/jail/cliscripts/create_queue_cmd
    ports:
      - 8080:8080
      - 9000:9000
    tmpfs: /dev/shm
    ulimits:
      nofile:
        soft: 2448
        hard: 38048
    environment:
      username_admin_globalaccesslevel: admin
      username_admin_password: admin
      system_scaling_maxconnectioncount: 100
      security-opt: "apparmor:unconfined"

  connect:
    depends_on:
      - solace
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms
