---
version: '3.5'
services:

  nginx-proxy:
    #image: reiz/nginx_proxy:latest
    build:
      context: ../../connect/connect-servicenow-source/repro-read-timeout/
    hostname: nginx-proxy
    container_name: nginx-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-servicenow-source/repro-read-timeout/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  connect:
    volumes:
      - ../../connect/connect-servicenow-source/repro-read-timeout/logging.properties:/tmp/logging.properties
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-servicenow
      KAFKA_OPTS: -Djava.util.logging.config.file=/tmp/logging.properties