---
services:

  connect:
    volumes:
      - ../../connect/connect-jdbc-snowflake-source/snowflake_key.p8:/tmp/snowflake_key.p8
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
      # JDK 17
      KAFKA_OPTS: "--add-opens=java.base/java.nio=ALL-UNNAMED"