---
services:

  connect:
    volumes:
      - ../../connect/connect-datagen-source/schemas:/tmp/schemas
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen