---
services:
  replicator:
    image: confluentinc/cp-enterprise-replicator-executable:${TAG}
    hostname: replicator
    container_name: replicator
    volumes:
        - ../../ccloud/replicator/executable-onprem-to-cloud-consumer.properties:/etc/replicator/consumer.properties
        - ../../ccloud/replicator/executable-onprem-to-cloud-producer.properties:/etc/replicator/producer.properties
        - ../../ccloud/replicator/executable-onprem-to-cloud-replicator.properties:/etc/replicator/replication.properties
    environment:
      WHITELIST: executable-products

  control-center:
    environment:
      CONTROL_CENTER_CONNECT_CLUSTER: http://replicator:8083
      CONTROL_CENTER_CONNECT_MYCONNECT_CLUSTER: http://replicator:8083
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_KAFKA_MYCLUSTER_BOOTSTRAP_SERVERS: 'broker:9092'
      CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: "false"
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1