---
services:


  httpserver:
    build:
      context: ../../connect/connect-http-sink/httpserver
    hostname: httpserver
    container_name: httpserver
    ports:
      - "9006:9006"


  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    links:
      - httpserver
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-http-sink/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN