---
services:
  databricks-sql-cli:
    build: ../../connect/connect-jdbc-databricks-source/databricks # Build the Docker image using the Dockerfile in the current directory
    container_name: databricks-sql-cli-container # Assign a friendly name to the container
    environment:
      DATABRICKS_SERVER_HOSTNAME: "${DATABRICKS_HOST}"
      DATABRICKS_HTTP_PATH: "${DATABRICKS_HTTP_PATH}"
      DATABRICKS_ACCESS_TOKEN: "${DATABRICKS_TOKEN}"
    
  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
      KAFKA_OPTS: "--add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED"