---
services:

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-http-v2
      KAFKA_OPTS: "--add-opens=java.base/java.net=ALL-UNNAMED"

  httpserver:
    build:
      context: ../../connect/connect-http-sink/httpserver
    hostname: httpserver
    container_name: httpserver
    ports:
      - "9006:9006"