---
services:

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-http-v2

  httpserver:
    build:
      context: ../../connect/connect-http-sink/httpserver-oauth2
    hostname: httpserver
    container_name: httpserver
    ports:
      - "9006:9006"