---
version: '3.5'
services:
  umserver:
    image: softwareag/universalmessaging-server:10.11
    hostname: umserver
    container_name: umserver
    ports:
      - 9000:9000
    tmpfs: /dev/shm
    ulimits:
      nofile:
        soft: 2448
        hard: 38048
    environment:
      REALM_NAME: umtest
      INIT_JAVA_MEM_SIZE: 2048
      MAX_JAVA_MEM_SIZE: 2048
      MAX_DIRECT_MEM_SIZE: 2G
      BASIC_AUTH_ENABLE: N
      BASIC_AUTH_MANDATORY: N

  connect:
    depends_on:
      - umserver
    volumes:
        - ../../connect/connect-jms-sag-um-source/nClient.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/nClient.jar
        - ../../connect/connect-jms-sag-um-source/nJMS.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/nJMS.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms
