---
services:
  connect:
    volumes:
        - ../../connect/connect-gcp-bigquery-sink/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/wepay-kafka-connect-bigquery