---
version: '3.5'
services:

  oracle-datagen:
    build:
      context: ../../connect/connect-cdc-oracle19-source/oracle-datagen/
    hostname: oracle-datagen
    container_name: oracle-datagen
    
  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-cdc-oracle19-source/ora-setup-scripts-pdb-table:/opt/oracle/scripts/setup
    environment:
      ORACLE_PWD: Admin123

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - oracle
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-cdc
