---
version: '3.5'
services:
  oracle:
    image: wnameless/oracle-xe-11g-r2 # https://github.com/wnameless/docker-oracle-xe-11g
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../connect-jdbc-oracle11-source/00-oracle-init.sql:/docker-entrypoint-initdb.d/00-oracle-init.sql
      - ../connect-jdbc-oracle11-source/01-create-table.sh:/docker-entrypoint-initdb.d/01-create-table.sh
    environment:
      ORACLE_ALLOW_REMOTE: "true"

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - oracle
    volumes:
        - ../connect-jdbc-oracle11-source/ojdbc6.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/ojdbc6.jar
