---
services:

  connect:
    volumes:
      - ../../connect/connect-jdbc-snowflake-sink/snowflake_key.p8:/tmp/snowflake_key.p8
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc