---
version: '3.5'
services:

  connect:
    volumes:
      - ../../connect/connect-jdbc-snowflake-sink/snowflake_key.p8:/tmp/snowflake_key.p8
      - ../../connect/connect-jdbc-snowflake-sink/snowflake-jdbc-3.13.26.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/snowflake-jdbc-3.13.26.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc