version: '3.5'
services:

    ####
    #
    # This file overrides values from environment/plaintext/docker-compose.yml
    #
    ####

    zookeeper:
        volumes:
        - ../../environment/sasl-plain/zookeeper/zookeeper.sasl.jaas.config:/etc/kafka/zookeeper_server_jaas.conf
        environment:
            KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf
                -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                -Dzookeeper.allowSaslFailedClients=false
                -Dzookeeper.requireClientAuthScheme=sasl

    broker:
        volumes:
            - ../../environment/sasl-plain/kafka/kafka.jaas.conf:/etc/kafka/kafka_server_jaas.conf
            - ../../environment/sasl-plain/client.properties:/tmp/client.properties
        environment:
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SASL_PLAINTEXT,HOST:SASL_PLAINTEXT
            KAFKA_LISTENERS: BROKER://:9092,HOST://:29092
            KAFKA_ADVERTISED_LISTENERS: BROKER://broker:9092,HOST://localhost:29092
            KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
                    org.apache.kafka.common.security.plain.PlainLoginModule required \
                    username="broker" \
                    password="broker" \
                    user_broker="broker" \
                    user_controlcenter="controlcenter-secret" \
                    user_schemaregistry="schemaregistry-secret" \
                    user_ksqldb="ksqldb-secret" \
                    user_connect="connect-secret" \
                    user_sftp="sftp-secret" \
                    user_client="client-secret";
            KAFKA_LISTENER_NAME_HOST_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_LISTENER_NAME_HOST_PLAIN_SASL_JAAS_CONFIG: |
                    org.apache.kafka.common.security.plain.PlainLoginModule required \
                    username="broker" \
                    password="broker" \
                    user_broker="broker" \
                    user_controlcenter="controlcenter-secret" \
                    user_schemaregistry="schemaregistry-secret" \
                    user_ksqldb="ksqldb-secret" \
                    user_connect="connect-secret" \
                    user_sftp="sftp-secret" \
                    user_client="client-secret";
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
            CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
            CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONFLUENT_METRICS_REPORTER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"client\" \
                password=\"client-secret\";"
            KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

    connect:
        volumes:
            - ../../environment/sasl-plain/client.properties:/tmp/client.properties
        environment:
            # Configure the Connect workers to use SASL/PLAIN.
            CONNECT_SASL_MECHANISM: PLAIN
            CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
            # JAAS
            CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # producer
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # consumer
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # producer
            CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
            CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # consumer
            CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
            CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"

    connect2:
        volumes:
            - ../../environment/sasl-plain/client.properties:/tmp/client.properties
        environment:
            # Configure the Connect workers to use SASL/PLAIN.
            CONNECT_SASL_MECHANISM: PLAIN
            CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
            # JAAS
            CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # producer
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # consumer
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # producer
            CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
            CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # consumer
            CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
            CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"

    connect3:
        volumes:
            - ../../environment/sasl-plain/client.properties:/tmp/client.properties
        environment:
            # Configure the Connect workers to use SASL/PLAIN.
            CONNECT_SASL_MECHANISM: PLAIN
            CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
            # JAAS
            CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # producer
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # consumer
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # producer
            CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
            CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"
            # consumer
            CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
            CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"connect\" \
                password=\"connect-secret\";"


    schema-registry:
        volumes:
            - ../../environment/sasl-plain/client.properties:/tmp/client.properties
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
            SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
            SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"schemaregistry\" \
                password=\"schemaregistry-secret\";"

    ksqldb-server:
        environment:
            KSQL_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KSQL_SASL_MECHANISM: PLAIN
            KSQL_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"ksqldb\" \
                password=\"ksqldb-secret\";"
            # producer
            KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"ksqldb\" \
                password=\"ksqldb-secret\";"
            KSQL_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
            # consumer
            KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"ksqldb\" \
                password=\"ksqldb-secret\";"
            KSQL_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN

    control-center:
        environment:
            CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"client\" \
                password=\"client-secret\";"
            CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
            CONTROL_CENTER_KAFKA_MYCLUSTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
            CONTROL_CENTER_KAFKA_MYCLUSTER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
                username=\"client\" \
                password=\"client-secret\";"
            CONTROL_CENTER_KAFKA_MYCLUSTER_SASL_MECHANISM: PLAIN

    # https://github.com/conduktor/conduktor-platform/blob/main/doc/Configuration.md
    conduktor:
        volumes:
            - ../../environment/sasl-plain/conduktor/platform-config.yaml:/tmp/platform-config.yaml