---
version: '3.5'
services:
  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-cdc-oracle21-source/ora-setup-scripts-cdb-table:/opt/oracle/scripts/setup
    environment:
      ORACLE_PWD: Admin123

  connect:
    depends_on:
      - oracle
    volumes:
        - ../../connect/connect-jms-oracle21-source/ojdbc8.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/ojdbc8.jar
        - ../../connect/connect-jms-oracle21-source/aqapi.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/aqapi.jar
        - ../../connect/connect-jms-oracle21-source/jta-1.1.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms/lib/jta-1.1.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms
