config:
  http:
    baseurl: https://api.telemetry.confluent.cloud/
    timeout: 60
  listener: 0.0.0.0:2112
  noTimestamp: false
  delay: 60
  granularity: PT1M
rules:
  - clusters:
      - :CCLOUD_CLUSTER:
    # connectors:
    #   - $CCLOUD_CONNECTOR
    # ksqls:
    #   - $CCLOUD_KSQL
    metrics:
      - io.confluent.kafka.server/received_bytes
      - io.confluent.kafka.server/sent_bytes
      - io.confluent.kafka.server/received_records
      - io.confluent.kafka.server/sent_records
      - io.confluent.kafka.server/retained_bytes
      - io.confluent.kafka.server/active_connection_count
      - io.confluent.kafka.server/request_count
      - io.confluent.kafka.server/partition_count
      - io.confluent.kafka.server/successful_authentication_count
      # - io.confluent.kafka.connect/sent_bytes
      # - io.confluent.kafka.connect/received_bytes
      # - io.confluent.kafka.connect/received_records
      # - io.confluent.kafka.connect/sent_records
      # - io.confluent.kafka.connect/dead_letter_queue_records
      # - io.confluent.kafka.ksql/streaming_unit_count
    labels:
      - kafka_id
      - topic
      - type