---
version: '3.5'
services:

  postgres:
    build:
      context: ../../connect/connect-jdbc-postgresql-sink/mtls
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
     - ../../connect/connect-jdbc-postgresql-sink/mtls/my-postgres.conf:/etc/postgresql/postgresql.conf
     - ../../connect/connect-jdbc-postgresql-sink/mtls/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - postgres
    volumes:
      - ../../connect/connect-jdbc-postgresql-sink/mtls/ca.crt:/tmp/ca.crt
      - ../../connect/connect-jdbc-postgresql-sink/mtls/client.crt:/tmp/client.crt
      - ../../connect/connect-jdbc-postgresql-sink/mtls/client.key.pk8:/tmp/client.key.pk8
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
      KAFKA_OPTS: -Djavax.net.debug=all