---
services:
  connect:
    volumes:
      - ../../connect/connect-azure-synapse-analytics-sink/data:/data
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-azure-sql-dw
