---
version: '3.5'
services:
  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-cdc-oracle12-source/ora-setup-scripts-cdb-table:/opt/oracle/scripts/setup
      - ../../connect/connect-cdc-oracle12-source/ora-startup-scripts-cdb-table:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: Admin123

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - oracle
    volumes:
        - ../../connect/connect-cdc-oracle12-source/confluentinc-kafka-connect-oracle-cdc-0.1.2-rc-6e1027a-preview:/usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-cdc-0.1.2-rc-6e1027a-preview
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-oracle-cdc-0.1.2-rc-6e1027a-preview
