---
services:
  connect:
    volumes:
        - ../../connect/connect-jdbc-gcp-bigquery-source/keyfile.json:/tmp/keyfile.json:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc




