---
version: '3.5'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - ../../connect/connect-jdbc-sqlserver-source/ssl/mssql.conf:/var/opt/mssql/mssql.conf
      - ../../connect/connect-jdbc-sqlserver-source/ssl/mssql.pem:/tmp/mssql.pem
      - ../../connect/connect-jdbc-sqlserver-source/ssl/mssql.key:/tmp/mssql.key
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: "Standard"
      SA_PASSWORD: "Password!"

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - sqlserver
    volumes:
        - ../../connect/connect-jdbc-sqlserver-source/sqljdbc_12.2/enu/mssql-jdbc-12.2.0.jre11.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/mssql-jdbc-12.2.0.jre11.jar
        - ../../connect/connect-jdbc-sqlserver-source/ssl/truststore.jks:/tmp/truststore.jks
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc