---
version: '3.5'
services:
  connect:
    volumes:
        - ../../connect/connect-gcs-sink/keyfile.json:/root/keyfiles/keyfile.json:ro
        - ../../environment/2way-ssl/security:/etc/kafka/secrets
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-gcs