---
services:
  connect:
    volumes:
      - ../../connect/connect-filepulse-source/data:/data
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/streamthoughts-kafka-connect-file-pulse