---
version: '3.5'
services:
  oracle:
    # You need to build this image first, following the instructions at
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    image: ${ORACLE_IMAGE}
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../connect/connect-jdbc-oracle12-source/ora-setup-scripts:/opt/oracle/scripts/setup
    environment:
      ORACLE_PWD: Admin123

  connect:
    depends_on:
      - oracle
    volumes:
      - ../../connect/connect-jdbc-oracle12-source/ssl/truststore.jks:/tmp/truststore.jks
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
      KAFKA_OPTS: -Djavax.net.ssl.trustStore=/tmp/truststore.jks
                  -Djavax.net.ssl.trustStorePassword=welcome123
                  # -Djavax.net.debug=all