---
services:

  nginx-proxy:
    image: reiz/nginx_proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-salesforce-pushtopics-source/nginx-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  sfdx-cli:
    image: vdesabou/sfdx-cli:latest # forked from salestrip/sfdx-cli to add plugin sfpowerkit
    hostname: sfdx-cli
    container_name: sfdx-cli
    command: "sleep infinity"
    volumes:
    - ../../connect/connect-salesforce-pushtopics-source/MyLeadPushTopics.apex:/tmp/MyLeadPushTopics.apex

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce
    #dns: 0.0.0.0