---
version: '3.5'
services:

  jms-receiver:
    build:
      context: ../../connect/connect-jms-weblogic-sink/jms-receiver/
    hostname: jms-receiver
    container_name: jms-receiver
    volumes:
        - ../../connect/connect-jms-weblogic-sink/jms-receiver/lib/wlthint3client.jar:/tmp/wlthint3client.jar
        - ../../connect/connect-jms-weblogic-sink/jms-receiver/lib/weblogic.jar:/tmp/weblogic.jar
        - ../../connect/connect-jms-weblogic-sink/jms-receiver/target/jms-receiver-1.0.0.jar:/jms-receiver-1.0.0.jar
        
  weblogic-jms:
    image: weblogic-jms:latest
    hostname: weblogic-jms
    container_name: weblogic-jms
    ports:
      - '7001:7001'

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - weblogic-jms
    volumes:
        - ../../connect/connect-jms-weblogic-sink/jms-receiver/lib/wlthint3client.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/wlthint3client.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink
      # CONNECT_LOG4J_ROOT_LOGLEVEL: TRACE
