---
version: '3.5'
services:
  broker-us:
      volumes:
        - ../../environment/mdc-sasl-plain/client/client.properties:/etc/kafka/client.properties

  broker-europe:
      volumes:
        - ../../environment/mdc-sasl-plain/client/client.properties:/etc/kafka/client.properties

  connect-us:
    volumes:
        - ../../replicator/executable/consumer-europe-sasl-plain.properties:/etc/kafka/consumer-europe.properties
        - ../../replicator/executable/producer-europe-sasl-plain.properties:/etc/kafka/producer-europe.properties
        - ../../replicator/executable/replication-europe.properties:/etc/kafka/replication-europe.properties
        - ../../replicator/executable/consumer-us-sasl-plain.properties:/etc/kafka/consumer-us.properties
        - ../../replicator/executable/producer-us-sasl-plain.properties:/etc/kafka/producer-us.properties
        - ../../replicator/executable/replication-us.properties:/etc/kafka/replication-us.properties
    entrypoint: ["sh", "-c", "sleep 2073600"]

  connect-europe:
    volumes:
        - ../../replicator/executable/consumer-europe-sasl-plain.properties:/etc/kafka/consumer-europe.properties
        - ../../replicator/executable/producer-europe-sasl-plain.properties:/etc/kafka/producer-europe.properties
        - ../../replicator/executable/replication-europe.properties:/etc/kafka/replication-europe.properties
        - ../../replicator/executable/consumer-us-sasl-plain.properties:/etc/kafka/consumer-us.properties
        - ../../replicator/executable/producer-us-sasl-plain.properties:/etc/kafka/producer-us.properties
        - ../../replicator/executable/replication-us.properties:/etc/kafka/replication-us.properties
    entrypoint: ["sh", "-c", "sleep 2073600"]