---
version: '3.5'
services:

  # getting weird "Couldn't create directory: Failure", so created image from this PR https://github.com/atmoz/sftp/pull/164
  # https://github.com/amaysim-au/docker-sftp/tree/chroot-user
  # docker build -t vdesabou/sftp .
  # docker push vdesabou/sftp
  sftp-server:
    image: vdesabou/sftp
    hostname: sftp-server
    container_name: sftp-server
    ports:
      - "2222:22"
    command: foo:pass:::upload

  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    restart: unless-stopped
    ports:
      - 4040:4040
    links:
      - sftp-server
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-sftp-source/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN