---
version: '3.5'
services:
  squid:
    image: ubuntu/squid
    hostname: squid
    container_name: squid
    ports:
      - "3128:3128"

  connect:
    volumes:
      - ../../connect/connect-snowflake-sink/data:/data
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/snowflakeinc-snowflake-kafka-connector
      JDBC_TRACE: "true"
      # CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
      # CONNECT_LOG4J_LOGGERS: org.reflections=ERROR,com.snowflake.kafka.connector=TRACE,net.snowflake.client.jdbc=TRACE
    #dns: 0.0.0.0
