---
version: '3.5'
services:
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
    hostname: hadoop
    container_name: hadoop
    ports:
      - "9000:9000"
      - "50070:50070"

  connect:
    volumes:
        - ../../connect/connect-hdfs2-sink/confluentinc-kafka-connect-hdfs-5.0.4-SNAPSHOT:/usr/share/confluent-hub-components/confluentinc-kafka-connect-hdfs/confluentinc-kafka-connect-hdfs-5.0.4-SNAPSHOT
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-hdfs/confluentinc-kafka-connect-hdfs-5.0.4-SNAPSHOT
