---
services:
  openldap:
    image: osixia/openldap:1.3.0
    hostname: openldap
    container_name: openldap
    ports:
        - 389:389
        - 636:636
    environment:
        LDAP_ORGANISATION: "ConfluentDemo"
        LDAP_DOMAIN: "confluentdemo.io"
        LDAP_BASE_DN: "dc=confluentdemo,dc=io"
        LDAP_TLS_CRT_FILENAME: server.crt
        LDAP_TLS_KEY_FILENAME: server.key
        LDAP_TLS_CA_CRT_FILENAME: ca.crt
        LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
      - ../../other/cp-ansible-playground/ldap/ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ../../other/cp-ansible-playground/ldap/ldap_certs:/container/service/slapd/assets/certs
    command: "--copy-service --loglevel debug"

  broker1:
    volumes:
      - ../../other/cp-ansible-playground/ldap/ldap_certs/ldap_truststore.jks:/tmp/ldap_certs/ldap_truststore.jks

  broker2:
    volumes:
      - ../../other/cp-ansible-playground/ldap/ldap_certs/ldap_truststore.jks:/tmp/ldap_certs/ldap_truststore.jks

  broker3:
    volumes:
      - ../../other/cp-ansible-playground/ldap/ldap_certs/ldap_truststore.jks:/tmp/ldap_certs/ldap_truststore.jks