---
services:
  connect-us:
    volumes:
      - ../../multi-data-center/kafka-offsets-migrator/requirements.txt:/tmp/requirements.txt
      - ../../multi-data-center/kafka-offsets-migrator/offset_translator.py:/tmp/offset_translator.py