---
services:

  sql-datagen:
    build:
      context: ../../connect/connect-debezium-postgresql-source/postgres-datagen/
    hostname: sql-datagen
    container_name: sql-datagen
    profiles:
    - sql_datagen
    volumes:
      - ../../connect/connect-debezium-postgresql-source/postgres-datagen/target/sql-datagen-1.0-SNAPSHOT-jar-with-dependencies.jar:/sql-datagen-1.0-SNAPSHOT-jar-with-dependencies.jar

  postgres:
    image: debezium/postgres:15-alpine
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres

  connect:
    depends_on:
      - postgres
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/debezium-debezium-connector-postgresql
