---
services:

  postgres:
    build:
      context: ../../connect/connect-jdbc-postgresql-source/ssl
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
     - ../../connect/connect-jdbc-postgresql-source/ssl/my-postgres.conf:/etc/postgresql/postgresql.conf
     - ../../connect/connect-jdbc-postgresql-source/ssl/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf

  connect:
    depends_on:
      - postgres
    volumes:
      - ../../connect/connect-jdbc-postgresql-source/ssl/ca.crt:/tmp/ca.crt
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
      # KAFKA_OPTS: -Djavax.net.debug=all