lowercaseOutputName: true
rules:
- pattern: 'kafka.consumer<type=app-info, client-id=(.+)><>(.+): (.+)'
  value: 1
  name: kafka_consumer_app_info
  labels:
    client-id: $1
    $2: $3
  type: UNTYPED
- pattern : 'kafka.consumer<type=(.+), client-id=(.+), node-id=(.+)><>(.+):'
  name: kafka_consumer_$1_$4
  type: GAUGE
  labels:
    client-id: "$2"
    host-id: "$3"
- pattern : 'kafka.consumer<type=(.+), client-id=(.+), topic=(.+), partition=(.+)><>(.+):'
  name: kafka_consumer_$1_$5
  type: GAUGE
  labels:
    client-id: "$2"
    topic: "$3"
    partition: "$4"
- pattern : 'kafka.consumer<type=(.+), client-id=(.+), topic=(.+)><>(.+):'
  name: kafka_consumer_$1_$4
  type: GAUGE
  labels:
    client-id: "$2"
    topic: "$3"
- pattern : 'kafka.consumer<type=(.+), client-id=(.+)><>(.+):'
  name: kafka_consumer_$1_$3
  type: GAUGE
  labels:
    client-id: "$2"
