---
version: '3.5'
services:
  hbase:
    image: daunnc/hbase:2.2.4 # https://github.com/pomadchin/hbase-docker
    hostname: hbase
    container_name: hbase

  connect:
    depends_on:
      - hbase
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-hbase