---
version: '3.5'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - ../../connect/connect-debezium-sqlserver-source/ssl/mssql.conf:/var/opt/mssql/mssql.conf
      - ../../connect/connect-debezium-sqlserver-source/ssl/mssql.pem:/tmp/mssql.pem
      - ../../connect/connect-debezium-sqlserver-source/ssl/mssql.key:/tmp/mssql.key
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: "Standard"
      SA_PASSWORD: "Password!"

  connect:
    depends_on:
      - sqlserver
    volumes:
        - ../../connect/connect-debezium-sqlserver-source/ssl/truststore.jks:/tmp/truststore.jks
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/debezium-debezium-connector-sqlserver