---
version: '3.5'
services:
  # https://pypi.org/project/azure-cosmos/
  azure-cosmos-client:
    build:
      context: ../../ccloud/fm-azure-cosmosdb-sink/azure-cosmos-client
    hostname: azure-cosmos-client
    container_name: azure-cosmos-client