---
services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_HOST: 172.%  # Allow docker containers to connect to mariadb

  connect:
    depends_on:
      - mariadb
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc